import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "WSL Installation",
      items: [
        "tutorial-wsl/sfu-vpn",
        "tutorial-wsl/why-wsl",
        "tutorial-wsl/wsl-installation_Windows",
        "tutorial-wsl/wsl-installation_macOS",
      ],
    },
    {
      type: "category",
      label: "Git Documentation",
      items: [
        "git_docs/advanced_git_workflows",
        "git_docs/basic_git_commands",
        "git_docs/club-guidelines",
        "git_docs/git_setup_and_config",
        "git_docs/introduction_to_git",
        "git_docs/resources",
        "git_docs/what_is_gitignore",
      ],
    },
    {
      type: "category",
      label: "Intro to Code Styling",
      items: [
        "code-styling/bad-code-styling",
        "code-styling/good-code-styling",
        "code-styling/why-code-style",
      ],
    },
  ],

  pmSidebar: [
    "intro-pm",
    {
      type: "category",
      label: "Project Management",
      items: ["pm/pm"],
    },
  ],

  execSidebar: [
    "intro-exec",
    {
      type: "category",
      label: "President Team",
      items: [
        "club-execs/presidents/president-team",
        "club-execs/presidents/business-president",
        "club-execs/presidents/tech-president",
      ],
    },
    {
      type: "category",
      label: "Technology Teams",
      items: [
        "club-execs/directors/director-of-tech",
        "club-execs/teams/tech-team",
      ],
    },
    {
      type: "category",
      label: "Events Team",
      items: [
        "club-execs/directors/director-of-event",
        "club-execs/teams/event-team",
      ],
    },
    {
      type: "category",
      label: "Strategy Team",
      items: [
        "club-execs/directors/director-of-strat",
        "club-execs/teams/strat-team",
      ],
    },
    {
      type: "category",
      label: "Communications Team",
      items: [
        "club-execs/directors/director-of-comms",
        "club-execs/teams/comm-team",
      ],
    },
  ],
};

export default sidebars;
